//! Build script. Two jobs, both keeping the launcher a single self-contained binary:
//!
//! 1. Embed the vendored Godot Mod Loader addon as byte arrays (`embed_addon`), so the
//!    launcher can inject it into a patched `vcb.pck` at runtime.
//!      - `vendor/godot-mod-loader/addons/…` → `res://addons/…`
//!    (The Mod Menu used to be embedded here too; it now lives in its own repo,
//!    `n-popescu/vcb-modmenu`, and the launcher downloads its latest release at runtime —
//!    see `src/modmenu.rs`.)
//!
//! 2. Bake the launcher's procedural icon into the executable so it shows on the app file
//!    *before* it is launched, not just in the running window/taskbar. The art comes from
//!    the same rasteriser the app uses at runtime (`src/icon_render.rs`, pulled in with
//!    `include!` so there is still no image file to ship). On Windows this embeds a
//!    multi-resolution `.ico` as the `.exe` icon resource (what Explorer shows). A bare
//!    macOS/Linux binary can't carry a file icon, so there is nothing to embed there —
//!    macOS uses a `.app` bundle and Linux a `.desktop` file, both produced from the
//!    `gen-icons` helper in CI; we still write the `.ico` into OUT_DIR on every target.

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/src/icon_render.rs"));

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    embed_addon(&manifest, &out_dir);

    // Icon: encode a multi-resolution .ico and, on Windows, embed it as the .exe icon.
    println!("cargo:rerun-if-changed=src/icon_render.rs");
    println!("cargo:rerun-if-changed=build.rs");
    let ico_path = out_dir.join("vcb-launcher.ico");
    write_ico(&ico_path);
    embed_windows_icon(&ico_path);
}

/// Embed the Godot Mod Loader addon (paths become `res://addons/...`).
fn embed_addon(manifest: &Path, out_dir: &Path) {
    let addons_root = manifest.join("vendor/godot-mod-loader/addons");
    println!("cargo:rerun-if-changed=vendor/godot-mod-loader");

    let mut files: Vec<PathBuf> = Vec::new();
    collect(&addons_root, &mut files);
    files.sort();

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    out.push_str("pub static EMBEDDED_ADDON_FILES: &[(&str, &[u8])] = &[\n");
    for path in &files {
        let rel = path.strip_prefix(&addons_root).unwrap();
        let res_path = format!("res://addons/{}", rel.to_string_lossy().replace('\\', "/"));
        out.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            res_path,
            path.to_string_lossy()
        ));
        println!("cargo:rerun-if-changed={}", path.to_string_lossy());
    }
    out.push_str("];\n");

    fs::write(out_dir.join("embedded_addon.rs"), out).unwrap();
}

fn collect(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            collect(&p, out);
        } else {
            out.push(p);
        }
    }
}

/// Encode the icon as a multi-resolution `.ico` (16..256 px) from the procedural source.
fn write_ico(path: &Path) {
    let mut dir = ico::IconDir::new(ico::ResourceType::Icon);
    for &n in &[16usize, 24, 32, 48, 64, 128, 256] {
        let image = ico::IconImage::from_rgba_data(n as u32, n as u32, render_rgba(n));
        dir.add_entry(ico::IconDirEntry::encode(&image).expect("encode .ico entry"));
    }
    let file = std::fs::File::create(path).expect("create .ico");
    dir.write(file).expect("write .ico");
}

// `winresource` is a Windows-host build-dependency (see Cargo.toml), so gate the reference
// to host-Windows compilation. CI builds the Windows target natively on a Windows runner,
// where host == target, so this runs exactly when the .exe is being produced.
#[cfg(windows)]
fn embed_windows_icon(ico_path: &Path) {
    let mut res = winresource::WindowsResource::new();
    res.set_icon(ico_path.to_str().expect("utf-8 ico path"));
    if let Err(e) = res.compile() {
        // Don't fail the build over the cosmetic icon; warn so it's visible in the log.
        println!("cargo:warning=could not embed the Windows icon resource: {e}");
    }
}

#[cfg(not(windows))]
fn embed_windows_icon(_ico_path: &Path) {}
