//! Build script: embed the vendored Godot Mod Loader addon into the binary.
//!
//! Every file under `vendor/godot-mod-loader/addons/` is turned into an
//! `(res_path, bytes)` pair so the launcher can inject the whole addon into a
//! patched `vcb.pck` at runtime — keeping the launcher a single self-contained
//! executable. The `res_path` is the path the file must live at inside the pck,
//! e.g. `vendor/…/addons/mod_loader/mod_loader.gd` → `res://addons/mod_loader/mod_loader.gd`.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let addons_root = manifest.join("vendor/godot-mod-loader/addons");

    println!("cargo:rerun-if-changed=vendor/godot-mod-loader");

    let mut files: Vec<PathBuf> = Vec::new();
    collect(&addons_root, &mut files);
    files.sort();

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    out.push_str("pub static EMBEDDED_ADDON_FILES: &[(&str, &[u8])] = &[\n");
    for path in &files {
        let rel = path.strip_prefix(&addons_root).unwrap();
        let res_path = format!("res://addons/{}", rel.to_string_lossy().replace('\\', "/"));
        // include_bytes! from an absolute path is stable and location-independent.
        out.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            res_path,
            path.to_string_lossy()
        ));
        println!("cargo:rerun-if-changed={}", path.to_string_lossy());
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("embedded_addon.rs");
    fs::write(&dest, out).unwrap();
}

fn collect(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            collect(&p, out);
        } else {
            out.push(p);
        }
    }
}
