//! Build script: embed the vendored Godot Mod Loader addon and the bundled Mod Menu mod
//! into the binary.
//!
//! Every file under `vendor/godot-mod-loader/addons/` is turned into an
//! `(res_path, bytes)` pair so the launcher can inject the whole addon into a
//! patched `vcb.pck` at runtime — keeping the launcher a single self-contained
//! executable. The `res_path` is the path the file must live at inside the pck,
//! e.g. `vendor/…/addons/mod_loader/mod_loader.gd` → `res://addons/mod_loader/mod_loader.gd`.
//!
//! Every file under `vendor/mod-menu/mods-unpacked/` is turned into an
//! `(zip_path, bytes)` pair so the launcher can write the Mod Menu into the game's
//! `mods/` folder as a `.zip` on enable-modding. The `zip_path` is the path inside that
//! zip, e.g. `vendor/mod-menu/mods-unpacked/npopescu-ModMenu/manifest.json`
//! → `mods-unpacked/npopescu-ModMenu/manifest.json`.

use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    embed_addon(&manifest, &out_dir);
    embed_mod_menu(&manifest, &out_dir);
}

/// Embed the Godot Mod Loader addon (paths become `res://addons/...`).
fn embed_addon(manifest: &Path, out_dir: &Path) {
    let addons_root = manifest.join("vendor/godot-mod-loader/addons");
    println!("cargo:rerun-if-changed=vendor/godot-mod-loader");

    let mut files: Vec<PathBuf> = Vec::new();
    collect(&addons_root, &mut files);
    files.sort();

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    out.push_str("pub static EMBEDDED_ADDON_FILES: &[(&str, &[u8])] = &[\n");
    for path in &files {
        let rel = path.strip_prefix(&addons_root).unwrap();
        let res_path = format!("res://addons/{}", rel.to_string_lossy().replace('\\', "/"));
        out.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            res_path,
            path.to_string_lossy()
        ));
        println!("cargo:rerun-if-changed={}", path.to_string_lossy());
    }
    out.push_str("];\n");

    fs::write(out_dir.join("embedded_addon.rs"), out).unwrap();
}

/// Embed the bundled Mod Menu mod (paths become `mods-unpacked/...` inside the zip).
fn embed_mod_menu(manifest: &Path, out_dir: &Path) {
    let menu_root = manifest.join("vendor/mod-menu");
    println!("cargo:rerun-if-changed=vendor/mod-menu");

    let mut files: Vec<PathBuf> = Vec::new();
    collect(&menu_root.join("mods-unpacked"), &mut files);
    files.sort();

    let mut out = String::new();
    out.push_str("// @generated by build.rs — do not edit.\n");
    out.push_str("pub static EMBEDDED_MOD_MENU_FILES: &[(&str, &[u8])] = &[\n");
    for path in &files {
        let rel = path.strip_prefix(&menu_root).unwrap();
        let zip_path = rel.to_string_lossy().replace('\\', "/");
        out.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            zip_path,
            path.to_string_lossy()
        ));
        println!("cargo:rerun-if-changed={}", path.to_string_lossy());
    }
    out.push_str("];\n");

    fs::write(out_dir.join("embedded_mod_menu.rs"), out).unwrap();
}

fn collect(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            collect(&p, out);
        } else {
            out.push(p);
        }
    }
}
