//! Mods the launcher bundles and installs automatically when runtime modding is enabled.
//!
//! Right now that's just the **Mod Menu** (`npopescu-ModMenu`) — the in-game Options ▸ Mods
//! list. Its files are embedded by `build.rs` (from `vendor/mod-menu/`) and written into the
//! game's `mods/` folder as a single `.zip`, so a freshly-patched install already has the
//! mod list without the player installing anything.

use std::io::{self, Write};
use std::path::Path;
use zip::write::{SimpleFileOptions, ZipWriter};
use zip::CompressionMethod;

// The embedded Mod Menu files: &[(zip_path, bytes)] where zip_path is the path inside the
// produced zip (e.g. `mods-unpacked/npopescu-ModMenu/manifest.json`). Generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/embedded_mod_menu.rs"));

/// File name written into the game's `mods/` folder.
pub const MOD_MENU_ZIP: &str = "npopescu-ModMenu.zip";

fn map_zip(e: zip::result::ZipError) -> io::Error {
    io::Error::new(io::ErrorKind::Other, format!("zip: {e}"))
}

/// Build the Mod Menu `.zip` (containing `mods-unpacked/npopescu-ModMenu/…`) in memory.
fn build_mod_menu_zip() -> io::Result<Vec<u8>> {
    let mut zip = ZipWriter::new(io::Cursor::new(Vec::new()));
    let opts = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);
    for (name, bytes) in EMBEDDED_MOD_MENU_FILES {
        zip.start_file(*name, opts).map_err(map_zip)?;
        zip.write_all(bytes)?;
    }
    let cursor = zip.finish().map_err(map_zip)?;
    Ok(cursor.into_inner())
}

/// Install (or refresh) the bundled Mod Menu into `mods_dir` as `npopescu-ModMenu.zip`.
///
/// Overwrites any previous copy so a Re-apply always ships the current version. Best-effort:
/// callers treat a failure here as non-fatal (modding still works, the list just isn't there).
pub fn install_mod_menu(mods_dir: &Path) -> io::Result<()> {
    std::fs::create_dir_all(mods_dir)?;
    let bytes = build_mod_menu_zip()?;
    std::fs::write(mods_dir.join(MOD_MENU_ZIP), bytes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Read;
    use zip::ZipArchive;

    #[test]
    fn mod_menu_files_are_embedded() {
        assert!(
            !EMBEDDED_MOD_MENU_FILES.is_empty(),
            "the Mod Menu must be embedded by build.rs"
        );
        let names: Vec<&str> = EMBEDDED_MOD_MENU_FILES.iter().map(|(n, _)| *n).collect();
        for required in [
            "mods-unpacked/npopescu-ModMenu/manifest.json",
            "mods-unpacked/npopescu-ModMenu/mod_main.gd",
            "mods-unpacked/npopescu-ModMenu/extensions/main.gd",
            "mods-unpacked/npopescu-ModMenu/scripts/mods_window.gd",
        ] {
            assert!(names.contains(&required), "missing embedded file: {required}");
        }
    }

    #[test]
    fn builds_a_readable_zip() {
        let bytes = build_mod_menu_zip().expect("build zip");
        let mut zip = ZipArchive::new(io::Cursor::new(bytes)).expect("valid zip");
        // manifest.json is present and parses.
        let mut f = zip
            .by_name("mods-unpacked/npopescu-ModMenu/manifest.json")
            .expect("manifest in zip");
        let mut s = String::new();
        f.read_to_string(&mut s).unwrap();
        assert!(s.contains("\"namespace\""), "manifest looks like JSON");
    }

    #[test]
    fn install_writes_the_zip() {
        let dir = std::env::temp_dir().join(format!("vcbl_bundled_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        install_mod_menu(&dir).expect("install");
        let zip_path = dir.join(MOD_MENU_ZIP);
        assert!(zip_path.is_file(), "zip written into mods dir");
        assert!(std::fs::metadata(&zip_path).unwrap().len() > 0);
        let _ = std::fs::remove_dir_all(&dir);
    }
}
