//! Turn a stock `vcb.pck` into a **mod-loading** `vcb.pck` by injecting the Godot Mod
//! Loader — without replacing the game or needing its script-encryption key.
//!
//! The original game ships GDScript as encrypted `.gdc`. We never decrypt it: the
//! original file bytes are copied through **verbatim**, and we only *add* the (plain
//! GDScript) Mod Loader addon and rewrite `project.binary` to register it. The pristine
//! original is kept as `vcb.pck.original` so "disable modding" is a one-file restore.
//!
//! Pipeline (`enable_modding`):
//! 1. Snapshot the pristine `vcb.pck` → `vcb.pck.original` (once), and always patch
//!    *from* that pristine copy so re-patching never double-injects.
//! 2. Read its directory + `project.binary`.
//! 3. Patch `project.binary`: add the `ModLoaderStore` + `ModLoader` autoloads (loaded
//!    first) and merge the loader's `class_name` globals into `_global_script_classes`.
//! 4. Repack: original files verbatim + the embedded addon + the patched `project.binary`.
//! 5. Ensure a `mods/` folder exists next to the game for players to drop mods into.

use crate::pck;
use crate::pckbuild::{self, OutFile, Source};
use crate::projbin::{GlobalClass, ProjectBinary};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

// The embedded Mod Loader addon: &[(res_path, bytes)]. Generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/embedded_addon.rs"));

pub const PCK_NAME: &str = "vcb.pck";
pub const BACKUP_NAME: &str = "vcb.pck.original";
pub const PROJECT_BINARY: &str = "res://project.binary";

/// The autoloads the loader needs, in load order (Store must precede ModLoader).
const AUTOLOADS: &[(&str, &str)] = &[
    ("ModLoaderStore", "res://addons/mod_loader/mod_loader_store.gd"),
    ("ModLoader", "res://addons/mod_loader/mod_loader.gd"),
];

/// A marker file that only exists once the addon is injected.
const MARKER: &str = "res://addons/mod_loader/mod_loader.gd";

pub fn pck_path(game_dir: &Path) -> PathBuf {
    game_dir.join(PCK_NAME)
}
pub fn backup_path(game_dir: &Path) -> PathBuf {
    game_dir.join(BACKUP_NAME)
}
pub fn mods_dir(game_dir: &Path) -> PathBuf {
    game_dir.join("mods")
}

/// Is this pck already Mod-Loader-patched?
pub fn is_patched(pck_file: &Path) -> bool {
    matches!(pck::extract_file(pck_file, MARKER), Ok(Some(_)))
}

/// Whether the game at `game_dir` currently has modding enabled.
pub fn modding_enabled(game_dir: &Path) -> bool {
    is_patched(&pck_path(game_dir))
}

#[derive(Debug)]
pub enum PatchError {
    NotAPck,
    Io(io::Error),
    BadProjectBinary,
}

impl std::fmt::Display for PatchError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            PatchError::NotAPck => write!(
                f,
                "vcb.pck is missing or not a Godot 3.x package this launcher can patch"
            ),
            PatchError::Io(e) => write!(f, "{e}"),
            PatchError::BadProjectBinary => {
                write!(f, "couldn't read project.binary inside vcb.pck")
            }
        }
    }
}
impl From<io::Error> for PatchError {
    fn from(e: io::Error) -> Self {
        PatchError::Io(e)
    }
}

/// The Mod Loader addon file set to inject: `&[(res_path, bytes)]`, the same shape as the
/// build-time-embedded `EMBEDDED_ADDON_FILES`. A web-downloaded copy (see `modloader.rs`)
/// is passed in this shape too, so the patch pipeline is source-agnostic.
pub type Addon<'a> = &'a [(&'a str, &'a [u8])];

/// The Mod Loader addon baked into the launcher at build time — the offline fallback / seed.
pub fn embedded_addon() -> Addon<'static> {
    EMBEDDED_ADDON_FILES
}

/// The Mod Loader `mod_loader_store.gd`, which carries `const MODLOADER_VERSION`.
pub const MODLOADER_STORE: &str = "res://addons/mod_loader/mod_loader_store.gd";

/// Read the Mod Loader version currently baked into `pck_file` (None if unpatched).
pub fn applied_version(pck_file: &Path) -> Option<String> {
    pck::extract_file(pck_file, MODLOADER_STORE)
        .ok()
        .flatten()
        .and_then(|b| crate::modloader::parse_version(&b))
}

/// The `class_name` globals declared by an addon file set, derived by scanning each `.gd`
/// for its `class_name` / `extends`. These get merged into `_global_script_classes` so the
/// loader's classes resolve at runtime.
pub fn global_classes_for(addon: Addon) -> Vec<GlobalClass> {
    let mut out = Vec::new();
    for &(res_path, bytes) in addon {
        if !res_path.ends_with(".gd") {
            continue;
        }
        let text = String::from_utf8_lossy(bytes);
        let mut class: Option<String> = None;
        let mut base: Option<String> = None;
        for line in text.lines() {
            let l = line.trim_end();
            if let Some(rest) = l.strip_prefix("class_name ") {
                class = Some(first_token(rest));
            } else if let Some(rest) = l.strip_prefix("extends ") {
                base = Some(first_token(rest).trim_matches('"').to_string());
            }
            // class_name / extends always sit at the top; stop once we have the class.
            if class.is_some() && (base.is_some() || l.starts_with("func ") || l.starts_with("var ")) {
                break;
            }
        }
        if let Some(class) = class {
            out.push(GlobalClass {
                // A script with no `extends` implicitly extends Reference in GDScript 3.x.
                base: base.unwrap_or_else(|| "Reference".to_string()),
                class,
                path: res_path.to_string(),
            });
        }
    }
    out
}

fn first_token(s: &str) -> String {
    s.trim()
        .split(|c: char| c.is_whitespace())
        .next()
        .unwrap_or("")
        .to_string()
}

/// Enable modding with the built-in (seed) Mod Loader — the offline default, and what the
/// tests exercise.
pub fn enable_modding(game_dir: &Path) -> Result<(), PatchError> {
    enable_modding_with(game_dir, embedded_addon())
}

/// Enable modding: patch `<game_dir>/vcb.pck` in place (keeping `vcb.pck.original`),
/// injecting the given Mod Loader `addon` file set. `addon` is either the embedded seed or a
/// web-downloaded copy (see `modloader.rs`), so a Re-apply / update always bakes in whichever
/// version the caller selected.
pub fn enable_modding_with(game_dir: &Path, addon: Addon) -> Result<(), PatchError> {
    let live = pck_path(game_dir);
    let backup = backup_path(game_dir);

    // Always patch from the pristine original. Snapshot it once if we don't have it.
    if !backup.exists() {
        if !live.is_file() {
            return Err(PatchError::NotAPck);
        }
        if pckbuild::read_dir(&live)?.is_none() {
            return Err(PatchError::NotAPck);
        }
        fs::copy(&live, &backup)?;
    }
    let source = if backup.is_file() { backup.clone() } else { live.clone() };

    let pck = pckbuild::read_dir(&source)?.ok_or(PatchError::NotAPck)?;

    // Patch project.binary (autoloads + global classes).
    let pb_bytes = pck::extract_file(&source, PROJECT_BINARY)
        .map_err(PatchError::Io)?
        .ok_or(PatchError::BadProjectBinary)?;
    let mut pb = ProjectBinary::parse(&pb_bytes).ok_or(PatchError::BadProjectBinary)?;
    pb.add_autoloads(AUTOLOADS);
    pb.merge_global_classes(&global_classes_for(addon));
    let patched_pb = pb.to_bytes();

    // Which added paths override originals (project.binary + every addon file).
    let addon_paths: std::collections::HashSet<&str> = addon.iter().map(|(p, _)| *p).collect();

    let mut files: Vec<OutFile> = Vec::with_capacity(pck.entries.len() + addon.len());
    for e in &pck.entries {
        if e.path == PROJECT_BINARY || addon_paths.contains(e.path.as_str()) {
            continue; // replaced/added below
        }
        files.push(OutFile {
            path: e.path.clone(),
            source: Source::Original { offset: e.offset, size: e.size, md5: e.md5 },
        });
    }
    files.push(OutFile { path: PROJECT_BINARY.to_string(), source: Source::Bytes(&patched_pb) });
    for &(res_path, bytes) in addon {
        files.push(OutFile { path: res_path.to_string(), source: Source::Bytes(bytes) });
    }

    // Write to a temp file next to the target, then swap in atomically.
    let tmp = game_dir.join("vcb.pck.patching.tmp");
    pckbuild::write_pck(&tmp, &source, &pck.header, &files)?;
    fs::rename(&tmp, &live)?;

    let _ = fs::create_dir_all(mods_dir(game_dir));
    // Install the in-game Mod Menu (Options ▸ Mods) from the latest copy cached from the
    // vcb-modmenu repo (fetched at startup). Best-effort: on a fresh offline install with no
    // cached copy this is skipped — modding still works, the player just won't have the list yet
    // (it lands on the next enable/Re-apply once online).
    let _ = crate::modmenu::install(&mods_dir(game_dir));
    Ok(())
}

/// Disable modding: restore the pristine `vcb.pck.original` over `vcb.pck`.
pub fn disable_modding(game_dir: &Path) -> Result<(), PatchError> {
    let backup = backup_path(game_dir);
    if !backup.is_file() {
        return Err(PatchError::Io(io::Error::new(
            io::ErrorKind::NotFound,
            "no vcb.pck.original to restore",
        )));
    }
    fs::copy(&backup, pck_path(game_dir))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn embedded_addon_is_present() {
        assert!(
            EMBEDDED_ADDON_FILES.len() > 20,
            "the whole addon should be embedded, got {}",
            EMBEDDED_ADDON_FILES.len()
        );
        // The two autoload scripts must exist at the paths we register.
        for (_, path) in AUTOLOADS {
            assert!(
                EMBEDDED_ADDON_FILES.iter().any(|(p, _)| p == path),
                "autoload script {path} must be embedded"
            );
        }
    }

    #[test]
    fn derives_known_global_classes() {
        let classes = global_classes_for(embedded_addon());
        let by_name = |n: &str| classes.iter().find(|c| c.class == n).cloned();

        let log = by_name("ModLoaderLog").expect("ModLoaderLog present");
        assert_eq!(log.base, "Node");
        assert_eq!(log.path, "res://addons/mod_loader/api/log.gd");

        let data = by_name("ModData").expect("ModData present");
        assert_eq!(data.base, "Resource");

        // A class_name with no `extends` line defaults to Reference.
        let setup = by_name("ModLoaderSetupUtils").expect("ModLoaderSetupUtils present");
        assert_eq!(setup.base, "Reference");

        // The autoload scripts have no class_name and must NOT be registered as globals.
        assert!(by_name("ModLoader").is_none());
        assert!(by_name("ModLoaderStore").is_none());

        assert!(classes.len() >= 20, "expected the addon's ~24 classes, got {}", classes.len());
    }

    // --- full pipeline against a realistic synthetic vcb.pck ---------------------------
    use crate::pckbuild::{read_dir, write_pck, OutFile as OF, PckHeader, Source as Src};
    use std::fs;
    use std::io::{Read, Seek, SeekFrom};

    fn read_entry(pck_file: &Path, e: &crate::pckbuild::PckEntry) -> Vec<u8> {
        let mut f = fs::File::open(pck_file).unwrap();
        f.seek(SeekFrom::Start(e.offset)).unwrap();
        let mut buf = vec![0u8; e.size as usize];
        f.read_exact(&mut buf).unwrap();
        buf
    }

    fn make_game_dir(tag: &str) -> PathBuf {
        let d = std::env::temp_dir().join(format!("vcbl_patch_{}_{}", std::process::id(), tag));
        let _ = fs::remove_dir_all(&d);
        fs::create_dir_all(&d).unwrap();
        d
    }

    // A vcb.pck resembling the real one: a project.binary (VCB-like classes + E/C
    // autoloads) plus a couple of "encrypted" game files we must preserve byte-for-byte.
    fn write_fake_vcb_pck(dir: &Path) -> (Vec<u8>, Vec<u8>) {
        let pb = crate::projbin::build_project_binary_for_test(
            &[("application/config/name", "Virtual Circuit Board"), ("application/run/main_scene", "res://src/main/main.tscn")],
            &[("Node", "Editor", "res://src/editor/editor.gd"), ("Node", "Assembler", "res://src/assembler/assembler.gd")],
            &[("E", "res://src/singletons/events.gd"), ("C", "res://src/singletons/constants.gd")],
        );
        let editor_gdc = vec![0xDEu8; 4096]; // stand-in for an encrypted .gdc
        let files = vec![
            OF { path: PROJECT_BINARY.to_string(), source: Src::Bytes(&pb) },
            OF { path: "res://src/editor/editor.gdc".to_string(), source: Src::Bytes(&editor_gdc) },
            OF { path: "res://icon.png".to_string(), source: Src::Bytes(&[1, 2, 3, 4, 5]) },
        ];
        let header = PckHeader { ver_major: 3, ver_minor: 5, ver_patch: 1 };
        write_pck(&pck_path(dir), &pck_path(dir), &header, &files).unwrap();
        (pb, editor_gdc)
    }

    #[test]
    fn enable_modding_patches_and_preserves_original() {
        let dir = make_game_dir("enable");
        let (_orig_pb, editor_gdc) = write_fake_vcb_pck(&dir);
        let original_pck_bytes = fs::read(pck_path(&dir)).unwrap();

        assert!(!modding_enabled(&dir), "starts unpatched");
        enable_modding(&dir).expect("enable modding");
        assert!(modding_enabled(&dir), "now patched");

        // Pristine original was snapshotted, untouched.
        assert_eq!(fs::read(backup_path(&dir)).unwrap(), original_pck_bytes);
        assert!(mods_dir(&dir).is_dir(), "mods/ folder created");
        // The Mod Menu is fetched from the vcb-modmenu repo and installed from cache (see
        // modmenu.rs); with no cache in a unit test it's simply skipped, so we don't assert it
        // here. modmenu::tests covers the install-from-zip path.

        let patched = read_dir(&pck_path(&dir)).unwrap().unwrap();

        // Original game file preserved byte-for-byte.
        let e = patched.find("res://src/editor/editor.gdc").expect("editor.gdc kept");
        assert_eq!(read_entry(&pck_path(&dir), e), editor_gdc, "encrypted file untouched");
        assert!(patched.find("res://icon.png").is_some());

        // Whole addon injected.
        for (res_path, _) in EMBEDDED_ADDON_FILES {
            assert!(patched.has(res_path), "addon file {res_path} injected");
        }

        // project.binary: autoloads first, in order; classes merged (keep game's own).
        let e = patched.find(PROJECT_BINARY).unwrap();
        let pb = read_entry(&pck_path(&dir), e);
        let order = crate::projbin::read_autoload_order_for_test(&pb);
        assert_eq!(
            order,
            vec![
                "autoload/ModLoaderStore".to_string(),
                "autoload/ModLoader".to_string(),
                "autoload/E".to_string(),
                "autoload/C".to_string(),
            ]
        );
        let names = crate::projbin::read_global_class_names_for_test(&pb);
        assert!(names.contains(&"Editor".to_string()) && names.contains(&"Assembler".to_string()));
        assert!(names.contains(&"ModLoaderLog".to_string()) && names.contains(&"ModData".to_string()));

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn enable_modding_is_idempotent() {
        let dir = make_game_dir("idem");
        write_fake_vcb_pck(&dir);

        enable_modding(&dir).unwrap();
        let after_first = fs::read(pck_path(&dir)).unwrap();
        let backup_after_first = fs::read(backup_path(&dir)).unwrap();

        // Re-patch: must patch from the pristine original again (no double injection).
        enable_modding(&dir).unwrap();
        let after_second = fs::read(pck_path(&dir)).unwrap();
        assert_eq!(after_first, after_second, "re-patching yields an identical pck");
        assert_eq!(backup_after_first, fs::read(backup_path(&dir)).unwrap(), "backup unchanged");

        // Exactly one copy of each class name.
        let patched = read_dir(&pck_path(&dir)).unwrap().unwrap();
        let e = patched.find(PROJECT_BINARY).unwrap();
        let names = crate::projbin::read_global_class_names_for_test(&read_entry(&pck_path(&dir), e));
        let mut sorted = names.clone();
        sorted.sort();
        sorted.dedup();
        assert_eq!(sorted.len(), names.len(), "no duplicate classes after re-patch");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn enable_with_custom_addon_source_injects_and_reads_version() {
        // Patch from an alternative Mod Loader file set (as a web-downloaded copy would be),
        // not the embedded seed: its files must be injected, its class_name registered, and
        // its MODLOADER_VERSION readable back out of the pck via applied_version().
        let dir = make_game_dir("custom_addon");
        write_fake_vcb_pck(&dir);

        let store = b"extends Node\nconst MODLOADER_VERSION = \"9.9.9\"\n".to_vec();
        let loader = b"extends Node\n".to_vec();
        let helper = b"class_name MyModThing\nextends Reference\n".to_vec();
        let addon: Vec<(&str, &[u8])> = vec![
            (MODLOADER_STORE, &store),
            ("res://addons/mod_loader/mod_loader.gd", &loader),
            ("res://addons/mod_loader/api/thing.gd", &helper),
        ];

        enable_modding_with(&dir, &addon).unwrap();
        assert!(modding_enabled(&dir));
        assert_eq!(applied_version(&pck_path(&dir)).as_deref(), Some("9.9.9"));

        let patched = read_dir(&pck_path(&dir)).unwrap().unwrap();
        assert!(patched.has("res://addons/mod_loader/api/thing.gd"), "custom addon file injected");
        let e = patched.find(PROJECT_BINARY).unwrap();
        let names = crate::projbin::read_global_class_names_for_test(&read_entry(&pck_path(&dir), e));
        assert!(names.contains(&"MyModThing".to_string()), "custom class registered as global");

        let _ = fs::remove_dir_all(&dir);
    }

    #[test]
    fn disable_modding_restores_vanilla() {
        let dir = make_game_dir("disable");
        write_fake_vcb_pck(&dir);
        let original = fs::read(pck_path(&dir)).unwrap();

        enable_modding(&dir).unwrap();
        assert!(modding_enabled(&dir));
        disable_modding(&dir).unwrap();
        assert!(!modding_enabled(&dir), "restored to vanilla");
        assert_eq!(fs::read(pck_path(&dir)).unwrap(), original, "byte-identical vanilla");

        let _ = fs::remove_dir_all(&dir);
    }
}
